FROM python:3.12-alpine AS builder

WORKDIR /app

# Installer dépendances système pour apprise
RUN apk add --no-cache build-base libffi-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Runtime
FROM python:3.12-alpine

WORKDIR /app

COPY --from=builder /app /app

CMD ["python", "app.py"]
